# Installs the FANUC TP / KAREL and ABB RAPID support into Notepad++ for this Windows user.
# Generated by robot-code-vscode scripts/make-notepadpp.mjs (Robot Code 26.109.7).
# Run:  powershell -ExecutionPolicy Bypass -File install.ps1      (with Notepad++ closed)
# A portable Notepad++ keeps these folders beside notepad++.exe instead - pass -Target <that folder>.
# uninstall.ps1 takes all of it out again.
param([string]$Target = (Join-Path $env:APPDATA 'Notepad++'))
$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path

# Notepad++ writes shortcuts.xml back when it closes, which would drop the Run menu entries.
if (Get-Process notepad++ -ErrorAction SilentlyContinue) {
    Write-Warning 'Close Notepad++ first, then run this again (it rewrites its settings when it closes).'
    exit 1
}

foreach ($dir in 'userDefineLangs', 'functionList') {
    New-Item -ItemType Directory -Force (Join-Path $Target $dir) | Out-Null
    Copy-Item (Join-Path $here "$dir\*") (Join-Path $Target $dir) -Force
}

# Notepad++ reads autoCompletion only from the folder notepad++.exe is in, never from %APPDATA%:
# a portable one is $Target itself, an installed one is under Program Files and needs admin.
$app = $Target
if (-not (Test-Path (Join-Path $Target 'notepad++.exe'))) {
    $app = (Get-ItemProperty 'HKLM:\SOFTWARE\Notepad++' -ErrorAction SilentlyContinue).'(default)'
    if (-not $app) { $app = Join-Path $env:ProgramFiles 'Notepad++' }
}
$acFrom = Join-Path $here 'autoCompletion\*'
$acTo = Join-Path $app 'autoCompletion'
try {
    Copy-Item $acFrom $acTo -Force
} catch {
    Write-Host "Ctrl+Space completion goes into $acTo - Windows will ask for admin rights to copy it."
    $q = { param($s) "'" + ($s -replace "'", "''") + "'" }
    $cmd = 'Copy-Item ' + (& $q $acFrom) + ' ' + (& $q $acTo) + ' -Force'
    try { Start-Process powershell -Verb RunAs -Wait -WindowStyle Hidden -ArgumentList '-NoProfile', '-Command', $cmd } catch { }
    if (-not (Test-Path (Join-Path $acTo 'FANUC KAREL.xml'))) {
        Write-Warning "Completion not installed: copy the files in autoCompletion\ into $acTo by hand (as admin)."
    }
}

# Function List finds a UDL's parser through overrideMap.xml: add our lines, keep the rest.
$map = Join-Path $Target 'functionList\overrideMap.xml'
if (-not (Test-Path $map)) {
    Set-Content $map -Encoding UTF8 -Value '<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
    <functionList>
        <associationMap>
        </associationMap>
    </functionList>
</NotepadPlus>'
}
$xml = Get-Content $map -Raw
foreach ($pair in @(@('fanuc_tp.xml', 'FANUC TP'), @('fanuc_karel.xml', 'FANUC KAREL'), @('abb_rapid.xml', 'ABB RAPID'))) {
    if ($xml -notmatch [regex]::Escape($pair[0])) {
        $line = '<association id="' + $pair[0] + '" userDefinedLangName="' + $pair[1] + '" />'
        $xml = $xml -replace '(\s*)</associationMap>', ('$1    ' + $line + '$1</associationMap>')
    }
}
Set-Content $map -Encoding UTF8 -Value $xml

# The robotcode tool (needs Node.js) and its Run menu entries, each with a Ctrl+Alt+Shift shortcut.
$toolDir = Join-Path $Target 'robotcode'
New-Item -ItemType Directory -Force $toolDir | Out-Null
Copy-Item (Join-Path $here 'robotcode.js') $toolDir -Force
$tool = Join-Path $toolDir 'robotcode.js'
$sc = Join-Path $Target 'shortcuts.xml'
if (Test-Path $sc) { [xml]$doc = Get-Content $sc -Raw -Encoding UTF8 }
else { [xml]$doc = '<?xml version="1.0" encoding="UTF-8" ?><NotepadPlus><InternalCommands /><Macros /><UserDefinedCommands /><PluginCommands /><ScintillaKeys /></NotepadPlus>' }
$udc = $doc.NotepadPlus.SelectSingleNode('UserDefinedCommands')
if (-not $udc) { $udc = $doc.NotepadPlus.AppendChild($doc.CreateElement('UserDefinedCommands')) }
foreach ($old in @($udc.SelectNodes('Command[starts-with(@name, "Robot Code: ")]'))) { [void]$udc.RemoveChild($old) }
# Key codes are Windows virtual keys: R=82 L=76 F=70 S=83 K=75
foreach ($c in @(@('Renumber lines', 'renumber', 82), @('Renumber labels', 'labels', 76), @('Format /POS', 'format', 70), @('Copy without positions', 'strip', 83), @('Check program', 'check', 75))) {
    $e = $doc.CreateElement('Command')
    $e.SetAttribute('name', 'Robot Code: ' + $c[0])
    $e.SetAttribute('Ctrl', 'yes'); $e.SetAttribute('Alt', 'yes'); $e.SetAttribute('Shift', 'yes'); $e.SetAttribute('Key', [string]$c[2])
    $e.InnerText = 'cmd /c node "' + $tool + '" ' + $c[1] + ' "$(FULL_CURRENT_PATH)" & pause'
    [void]$udc.AppendChild($e)
}
$doc.Save($sc)

Write-Host "FANUC TP, FANUC KAREL and ABB RAPID installed into $Target - start Notepad++."
Write-Host 'Run menu: Robot Code: Renumber lines / Renumber labels / Format /POS / Copy without positions / Check program (Ctrl+Alt+Shift+R/L/F/S/K). Save the file first; they edit it on disk.'
Write-Host ''
Write-Host 'ONE STEP LEFT: Notepad++ 8.9 and later protect the Run menu. On the next start it says shortcuts.xml'
Write-Host 'was modified and opens it: check the five "Robot Code: ..." commands, then choose'
Write-Host 'Run > Validate shortcuts.xml. Until then the Run menu commands do nothing.'
if (-not (Get-Command node -ErrorAction SilentlyContinue)) { Write-Warning 'Node.js was not found - the Run menu commands need it (https://nodejs.org, 18 or later).' }
