/**
 * The KAREL reference data (karelReference.ts, generated by
 * scripts/import-karel-reference.mjs) as the editor shows it: the extra lines of a built-in's hover,
 * hovers for statements, directives, data types, conditions, actions and clauses, the
 * %ENVIRONMENT check, and a read-only "KAREL Reference" page per entry.
 */
import * as vscode from 'vscode';
import { KAREL_BUILTIN_DETAILS, KAREL_LANGUAGE_DETAILS, type KBuiltinDetail, type KLanguageDetail } from './karelReference';
import type { KProgram } from './parser';
import { md } from '@core/util';

export const REFERENCE_SCHEME = 'robotcode-karel-ref';

/**
 * The %ENVIRONMENT groups ktrans does not load by itself. KTRANS V9.40-1 (WinOLPC) was asked for
 * every built-in, with and without the directive (2026-10-06): the core groups (REGOPE, SYSTEM,
 * PBCORE, UIF, FLBT ...) translate either way - their .ev files are in WinOLPC's support folder.
 * iRVision (CVIS), Data Transfer Between Robots (RPCC) and data monitoring (DAQ) are options: their
 * .ev comes with the option, so ktrans needs the directive AND a robot.ini pointing at a support
 * folder that has the file; without either it stops at "Id must be defined".
 */
export const ENV_NEEDS_DIRECTIVE = new Set(['CVIS', 'RPCC', 'DAQ']);

export function escapeMd(s: string): string {
  return s.replace(/[\\`*_[\]<>#|]/g, c => `\\${c}`);
}

/** the longest paragraphs are flattened tables; a hover shows their start */
export function clip(s: string, max = 500): string {
  return s.length <= max ? s : `${s.slice(0, s.lastIndexOf(' ', max))} …`;
}

function referenceLink(name: string, label = name): string {
  return `[${escapeMd(label)}](command:robotCode.karel.showReference?${encodeURIComponent(JSON.stringify([name]))})`;
}

function seeAlsoLine(names: string[] | undefined): string[] {
  const known = (names ?? []).filter(n => KAREL_BUILTIN_DETAILS[n] || KAREL_LANGUAGE_DETAILS[n]);
  return known.length ? ['', `See also: ${known.map(n => referenceLink(n)).join(', ')}`] : [];
}

/** the %ENVIRONMENT line of a built-in's hover: only the groups that need the directive say so plainly */
export function environmentLine(d: KBuiltinDetail | undefined, verbose: boolean): string[] {
  if (!d?.env) return [];
  if (ENV_NEEDS_DIRECTIVE.has(d.env)) return ['', `**Needs \`%ENVIRONMENT ${d.env}\`** in the program header (and the option's support files for ktrans).`];
  return verbose ? ['', `_\`%ENVIRONMENT\` group ${d.env}, which ktrans loads without the directive._`] : [];
}

/** what follows a built-in's parameters in the hover: related entries, the full entry */
export function builtinFooter(name: string, d: KBuiltinDetail | undefined, verbose: boolean): string[] {
  if (!d) return [];
  const out = environmentLine(d, verbose);
  if (verbose) out.push(...seeAlsoLine(d.seeAlso));
  out.push('', referenceLink(name, 'Full entry'));
  return out;
}

const KIND_TITLE: Record<string, string> = { statement: 'KAREL statement', directive: 'translator directive', 'data type': 'KAREL data type', condition: 'condition', action: 'action', clause: 'clause', operator: 'operator' };

function languageLines(name: string, e: KLanguageDetail, verbose: boolean): string[] {
  const out = [`**${escapeMd(name)}** — ${KIND_TITLE[e.kind] ?? e.kind}`, '', escapeMd(e.purpose.replace(/\.?$/, '.'))];
  if (e.syntax.length) out.push('', '```karel', ...e.syntax, '```');
  if (verbose) {
    if (e.details?.length) out.push('', ...e.details.map(d => `- ${escapeMd(clip(d))}`));
    out.push(...seeAlsoLine(e.seeAlso));
  }
  return out;
}

/**
 * The statement, directive, data type ... under the cursor. A phrase (OPEN FILE, WAIT FOR,
 * CONNECT TIMER) wins over a single word in it; %NAME is a directive only with its %.
 */
export function languageEntryAt(lineText: string, col: number): { name: string; entries: KLanguageDetail[]; start: number; end: number } | undefined {
  let best: { name: string; entries: KLanguageDetail[]; start: number; end: number } | undefined;
  for (const [name, entries] of Object.entries(KAREL_LANGUAGE_DETAILS)) {
    const words = name.split(' ').map(w => w.replace(/[$]/g, '\\$')).join('\\s+');
    const re = new RegExp(name.startsWith('%') ? `${words}\\b` : `(?<![%$\\w])${words}\\b`, 'gi');
    for (let m: RegExpExecArray | null; (m = re.exec(lineText));) {
      if (col < m.index || col > m.index + m[0].length) continue;
      if (!best || m[0].length > best.end - best.start) best = { name, entries, start: m.index, end: m.index + m[0].length };
    }
  }
  return best;
}

export function languageHover(name: string, entries: KLanguageDetail[], verbose: boolean, range: vscode.Range): vscode.Hover {
  const lines: string[] = [];
  entries.forEach((e, i) => lines.push(...(i ? ['', '---', ''] : []), ...languageLines(name, e, verbose)));
  lines.push('', referenceLink(name, 'Full entry'));
  return new vscode.Hover(md(...lines), range);
}

/**
 * Built-ins this program calls whose %ENVIRONMENT group it has not named: with `all`, every group;
 * else only those ktrans cannot load by itself. `needed` tells the two apart.
 */
export function missingEnvironment(prog: KProgram, isOwnName: (upper: string, line: number) => boolean, all = false): { upper: string; group: string; needed: boolean; span: KProgram['refs'][number]['span'] }[] {
  const named = new Set(prog.directives.filter(d => d.name === 'ENVIRONMENT').map(d => d.args.split(/\s+/)[0].toUpperCase()));
  const out: { upper: string; group: string; needed: boolean; span: KProgram['refs'][number]['span'] }[] = [];
  for (const r of prog.refs) {
    const group = KAREL_BUILTIN_DETAILS[r.upper]?.env;
    const needed = !!group && ENV_NEEDS_DIRECTIVE.has(group);
    if (!group || (!needed && !all) || named.has(group) || isOwnName(r.upper, r.line)) continue;
    out.push({ upper: r.upper, group, needed, span: r.span });
  }
  return out;
}

/** where %ENVIRONMENT goes: after the last directive of the header, else under the PROGRAM line */
export function environmentInsert(doc: vscode.TextDocument, prog: KProgram, group: string): vscode.TextEdit {
  const header = prog.directives.filter(d => prog.mainBegin === undefined || d.line < prog.mainBegin);
  const after = header.length ? Math.max(...header.map(d => d.line)) : prog.nameSpan?.line ?? 0;
  return vscode.TextEdit.insert(new vscode.Position(after + 1, 0), `%ENVIRONMENT ${group}${doc.eol === vscode.EndOfLine.CRLF ? '\r\n' : '\n'}`);
}

class EnvironmentFix implements vscode.CodeActionProvider {
  constructor(private progOf: (doc: vscode.TextDocument) => KProgram) {}
  provideCodeActions(doc: vscode.TextDocument, _range: vscode.Range, ctx: vscode.CodeActionContext): vscode.CodeAction[] {
    const groups = new Set(ctx.diagnostics.filter(d => d.code === 'karel.environment').map(d => /%ENVIRONMENT (\w+)/.exec(d.message)?.[1]).filter((g): g is string => !!g));
    return [...groups].map(g => {
      const a = new vscode.CodeAction(`Add %ENVIRONMENT ${g}`, vscode.CodeActionKind.QuickFix);
      a.edit = new vscode.WorkspaceEdit();
      a.edit.set(doc.uri, [environmentInsert(doc, this.progOf(doc), g)]);
      a.diagnostics = ctx.diagnostics.filter(d => d.code === 'karel.environment' && d.message.includes(`%ENVIRONMENT ${g}`));
      a.isPreferred = true;
      return a;
    });
  }
}

/** a whole entry, for the KAREL Reference page: nothing clipped */
export function referenceMarkdown(name: string): string {
  const b = KAREL_BUILTIN_DETAILS[name], ls = KAREL_LANGUAGE_DETAILS[name];
  const page = (n: string) => `${encodeURIComponent(n)}.md`;
  const also = (names?: string[]) => {
    const known = (names ?? []).filter(n => KAREL_BUILTIN_DETAILS[n] || KAREL_LANGUAGE_DETAILS[n]);
    return known.length ? ['', `**See also:** ${known.map(n => `[${escapeMd(n)}](${page(n)})`).join(', ')}`] : [];
  };
  const out: string[] = [];
  if (b) {
    out.push(`# ${escapeMd(name)}`, '', `_Built-in ${b.kind}${b.returns ? `, returns ${b.returns}` : ''}_`, '', escapeMd(b.purpose.replace(/\.?$/, '.')));
    if (b.params?.length) {
      out.push('', '## Parameters', '');
      for (const p of b.params) out.push(`- \`${p.name}\` _(${p.dir}${p.optional ? ', optional' : ''})_ : ${escapeMd(p.type)}${p.text ? ` — ${escapeMd(p.text)}` : ''}`);
    }
    if (b.notes?.length) out.push('', '## Details', '', ...b.notes.map(n => `- ${escapeMd(n)}`));
    if (b.env) out.push('', `\`%ENVIRONMENT ${b.env}\`${ENV_NEEDS_DIRECTIVE.has(b.env) ? ' — needed in the program header' : ' — ktrans loads this group without the directive'}`);
    out.push(...also(b.seeAlso));
  }
  for (const e of ls ?? []) {
    out.push(...(out.length ? ['', '---', ''] : []), `# ${escapeMd(name)}`, '', `_${KIND_TITLE[e.kind] ?? e.kind}_`, '', escapeMd(e.purpose.replace(/\.?$/, '.')));
    if (e.syntax.length) out.push('', '```karel', ...e.syntax, '```');
    if (e.details?.length) out.push('', ...e.details.map(d => `- ${escapeMd(d)}`));
    if (e.env) out.push('', `\`%ENVIRONMENT ${e.env}\``);
    out.push(...also(e.seeAlso));
  }
  if (!out.length) out.push(`# ${escapeMd(name)}`, '', 'No entry for this name.');
  return out.join('\n');
}

export function registerKarelReference(ctx: vscode.ExtensionContext, progOf: (doc: vscode.TextDocument) => KProgram): void {
  ctx.subscriptions.push(
    vscode.workspace.registerTextDocumentContentProvider(REFERENCE_SCHEME, {
      provideTextDocumentContent: uri => referenceMarkdown(decodeURIComponent(uri.path.replace(/^\//, '').replace(/\.md$/, ''))),
    }),
    vscode.languages.registerCodeActionsProvider({ language: 'fanuc-karel' }, new EnvironmentFix(progOf), { providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }),
    // with a name (a hover's link): that entry; without: pick one from the whole chapter
    vscode.commands.registerCommand('robotCode.karel.showReference', async (name?: string) => {
      if (!name) {
        const items = [
          ...Object.entries(KAREL_BUILTIN_DETAILS).map(([n, d]) => ({ label: n, description: `built-in ${d.kind}`, detail: d.purpose })),
          ...Object.entries(KAREL_LANGUAGE_DETAILS).map(([n, es]) => ({ label: n, description: es.map(e => e.kind).join(', '), detail: es[0].purpose })),
        ].sort((a, b) => a.label.replace(/^%/, '').localeCompare(b.label.replace(/^%/, '')));
        name = (await vscode.window.showQuickPick(items, { placeHolder: 'KAREL built-in, statement, directive, data type…', matchOnDescription: true, matchOnDetail: true }))?.label;
        if (!name) return;
      }
      const uri = vscode.Uri.from({ scheme: REFERENCE_SCHEME, path: `/${encodeURIComponent(name)}.md` });
      await vscode.commands.executeCommand('markdown.showPreview', uri);
    }),
  );
}
