# Removes everything install.ps1 added to Notepad++ for this Windows user.
# Generated by robot-code-vscode scripts/make-notepadpp.mjs (RUKUS Robotic Extensions {{VERSION}}).
# Run:  powershell -ExecutionPolicy Bypass -File uninstall.ps1    (with Notepad++ closed)
# Portable Notepad++: uninstall.ps1 -Target <the folder with notepad++.exe>
param([string]$Target = (Join-Path $env:APPDATA 'Notepad++'))
$ErrorActionPreference = 'Stop'

if (Get-Process notepad++ -ErrorAction SilentlyContinue) {
    Write-Warning 'Close Notepad++ first, then run this again (it rewrites its settings when it closes).'
    exit 1
}
$removed = @()
function Drop($path) { if (Test-Path -LiteralPath $path) { Remove-Item -LiteralPath $path -Recurse -Force; $script:removed += $path } }

Drop (Join-Path $Target 'userDefineLangs\FANUC TP.xml')
Drop (Join-Path $Target 'userDefineLangs\FANUC KAREL.xml')
Drop (Join-Path $Target 'functionList\fanuc_tp.xml')
Drop (Join-Path $Target 'functionList\fanuc_karel.xml')
Drop (Join-Path $Target 'userDefineLangs\ABB RAPID.xml')
Drop (Join-Path $Target 'functionList\abb_rapid.xml')
Drop (Join-Path $Target 'robotcode')

$map = Join-Path $Target 'functionList\overrideMap.xml'
if (Test-Path $map) {
    $xml = Get-Content $map -Raw
    $new = $xml -replace '\r?\n[ \t]*<association id="(fanuc_(tp|karel)|abb_rapid)\.xml"[^>]*/>', ''
    if ($new -ne $xml) { Set-Content $map -Encoding UTF8 -Value $new; $removed += "$map (2 lines)" }
}

$sc = Join-Path $Target 'shortcuts.xml'
if (Test-Path $sc) {
    [xml]$doc = Get-Content $sc -Raw -Encoding UTF8
    $udc = $doc.NotepadPlus.SelectSingleNode('UserDefinedCommands')
    $ours = if ($udc) { @($udc.SelectNodes('Command[starts-with(@name, "Robot Code: ") or starts-with(@name, "RUKUS: ")]')) } else { @() }
    if ($ours.Count) { foreach ($n in $ours) { [void]$udc.RemoveChild($n) }; $doc.Save($sc); $removed += "$sc ($($ours.Count) Run menu entries)" }
}

# autoCompletion sits beside notepad++.exe; under Program Files that needs admin
$app = $Target
if (-not (Test-Path (Join-Path $Target 'notepad++.exe'))) {
    $app = (Get-ItemProperty 'HKLM:\SOFTWARE\Notepad++' -ErrorAction SilentlyContinue).'(default)'
    if (-not $app) { $app = Join-Path $env:ProgramFiles 'Notepad++' }
}
$ac = @('FANUC TP.xml', 'FANUC KAREL.xml', 'ABB RAPID.xml') | ForEach-Object { Join-Path $app "autoCompletion\$_" } | Where-Object { Test-Path -LiteralPath $_ }
if ($ac) {
    try { $ac | ForEach-Object { Remove-Item -LiteralPath $_ -Force }; $removed += $ac }
    catch {
        Write-Host 'The completion files are in the Notepad++ program folder - Windows will ask for admin rights to remove them.'
        $cmd = ($ac | ForEach-Object { "Remove-Item -LiteralPath '" + ($_ -replace "'", "''") + "' -Force" }) -join '; '
        try { Start-Process powershell -Verb RunAs -Wait -WindowStyle Hidden -ArgumentList '-NoProfile', '-Command', $cmd } catch { }
        $left = $ac | Where-Object { Test-Path -LiteralPath $_ }
        if ($left) { Write-Warning ('Not removed (needs admin): ' + ($left -join ', ')) } else { $removed += $ac }
    }
}

if ($removed.Count) { Write-Host 'Removed:'; $removed | ForEach-Object { Write-Host "  $_" } } else { Write-Host 'Nothing of RUKUS Robotic Extensions was installed here.' }
