// One-off refactor helper: scope data/index lookups to the file's robot folder. Safe to re-run (idempotent).
import * as fs from 'node:fs';
function patch(file, pairs) {
  let t = fs.readFileSync(file, 'utf8');
  let n = 0;
  for (const [a, b] of pairs) {
    if (t.includes(b) && !t.includes(a)) continue; // already applied
    if (!t.includes(a)) { console.log('MISSING in', file, ':', a.slice(0, 90).replace(/\n/g, '\\n')); continue; }
    t = t.split(a).join(b); n++;
  }
  fs.writeFileSync(file, t);
  console.log(file, n, 'patches');
}
patch('packages/fanuc/src/tp/providers.ts', [
  ["function programLocation(s: Services, name: string): vscode.Location | undefined {\n  const info = s.index.get(name);", "function programLocation(s: Services, name: string, near?: vscode.Uri): vscode.Location | undefined {\n  const info = s.index.get(name, near);"],
  ["export async function callSitesOf(s: Services, name: string): Promise<vscode.Location[]> {\n  const out: vscode.Location[] = [];\n  for (const caller of s.index.callers(name)) {", "export async function callSitesOf(s: Services, name: string, near?: vscode.Uri): Promise<vscode.Location[]> {\n  const out: vscode.Location[] = [];\n  for (const caller of s.index.callers(name, near)) {"],
  ["export function dataHover(s: Services, prog: TpProgram, ref: TpDataRef): vscode.MarkdownString {\n  const kd = DATA_KIND_DOCS[ref.kind];\n  const lines: string[] = [];", "export function dataHover(s: Services, prog: TpProgram, ref: TpDataRef, uri: vscode.Uri): vscode.MarkdownString {\n  const kd = DATA_KIND_DOCS[ref.kind];\n  const lines: string[] = [];\n  const ds = s.data.dataset(uri);"],
  ["  const ctrl = s.data.comment(ref.kind, ref.index);\n  const inline = ref.comment;\n  const ws = s.index.inlineComment(ref.kind, ref.index);", "  const ctrl = ds?.comment(ref.kind, ref.index);\n  const inline = ref.comment;\n  const ws = s.index.inlineComment(ref.kind, ref.index, uri);"],
  ["  if (ctrl) lines.push('', `Controller comment: **${ctrl}**`);", "  if (ctrl) lines.push('', `Controller comment: **${ctrl}**${ds && s.data.datasets.length > 1 ? ` _(${ds.label})_` : ''}`);\n  if (!ds && s.data.datasets.length > 1) lines.push('', '_This file is not inside any robot backup folder, so no controller data is matched to it._');"],
  ["    const r = s.data.numregs.get(ref.index);\n    if (r && !live)", "    const r = ds?.numregs.get(ref.index);\n    if (r && !live)"],
  ["    const pr = s.data.posreg(ref.index);\n    if (pr) {\n      lines.push('', `Backup:", "    const pr = ds?.posreg(ref.index);\n    if (pr) {\n      lines.push('', `Backup:"],
  ["    const sr = s.data.strregs.get(ref.index);", "    const sr = ds?.strregs.get(ref.index);"],
  ["          const m = this.s.data.macro(t.name);\n          const lines = [`**${t.name}** — Macro instruction`];\n          if (m) { lines.push('', `Runs program **${m.progName}** (macro table entry ${m.index}).`); const info = this.s.index.get(m.progName); if (info?.comment)", "          const m = this.s.data.macro(t.name, doc.uri);\n          const lines = [`**${t.name}** — Macro instruction`];\n          if (m) { lines.push('', `Runs program **${m.progName}** (macro table entry ${m.index}).`); const info = this.s.index.get(m.progName, doc.uri); if (info?.comment)"],
  ["        case 'call': return new vscode.Hover(this.programHover(t.name, t.callKind), spanToRange(t.span));", "        case 'call': return new vscode.Hover(this.programHover(t.name, t.callKind, false, doc.uri), spanToRange(t.span));"],
  ["        case 'data': return new vscode.Hover(dataHover(this.s, prog, t.ref), spanToRange(t.ref.span));\n        case 'program': return new vscode.Hover(this.programHover(t.name, 'CALL', true), spanToRange(t.span));", "        case 'data': return new vscode.Hover(dataHover(this.s, prog, t.ref, doc.uri), spanToRange(t.ref.span));\n        case 'program': return new vscode.Hover(this.programHover(t.name, 'CALL', true, doc.uri), spanToRange(t.span));"],
  ["    if (line.motion && use === primary) lines.push('', this.describeMotion(prog, line.motion));", "    if (line.motion && use === primary) lines.push('', this.describeMotion(prog, line.motion, doc.uri));"],
  ["  private describeMotion(prog: TpProgram, m: NonNullable<TpProgram['lines'][number]['motion']>): string {", "  private describeMotion(prog: TpProgram, m: NonNullable<TpProgram['lines'][number]['motion']>, uri: vscode.Uri): string {"],
  ["      else { const pr = this.s.data.posreg(m.target.index); if (pr?.comment", "      else { const pr = this.s.data.posreg(m.target.index, 1, uri); if (pr?.comment"],
  ["  private programHover(name: string, kind: 'CALL' | 'RUN', isSelf = false): vscode.MarkdownString {\n    const info = this.s.index.get(name);", "  private programHover(name: string, kind: 'CALL' | 'RUN', isSelf = false, near?: vscode.Uri): vscode.MarkdownString {\n    const info = this.s.index.get(name, near);\n    const copies = this.s.index.all(name).length;"],
  ["      lines.push('', `[${vscode.workspace.asRelativePath(info.uri)}](${info.uri.toString()})`);\n      const callers = this.s.index.callers(name);", "      lines.push('', `[${vscode.workspace.asRelativePath(info.uri)}](${info.uri.toString()})${copies > 1 ? ` _(+${copies - 1} other cop${copies === 2 ? 'y' : 'ies'} in other robot folders)_` : ''}`);\n      const callers = this.s.index.callers(name, near);"],
  ["      case 'call': return programLocation(this.s, t.name);\n      case 'macro': { const m = this.s.data.macro(t.name); return m ? programLocation(this.s, m.progName) : undefined; }", "      case 'call': return programLocation(this.s, t.name, doc.uri);\n      case 'macro': { const m = this.s.data.macro(t.name, doc.uri); return m ? programLocation(this.s, m.progName, doc.uri) : undefined; }"],
  ["      case 'call': return callSitesOf(this.s, t.name);\n      case 'program': return callSitesOf(this.s, t.name);", "      case 'call': return callSitesOf(this.s, t.name, doc.uri);\n      case 'program': return callSitesOf(this.s, t.name, doc.uri);"],
  ["      .map(p => new vscode.SymbolInformation(p.name, p.kind === 'karel' ? vscode.SymbolKind.Class : vscode.SymbolKind.Module, p.comment ?? '', new vscode.Location(p.uri, new vscode.Position(0, 0))));", "      .map(p => new vscode.SymbolInformation(p.name, p.kind === 'karel' ? vscode.SymbolKind.Class : vscode.SymbolKind.Module, [p.comment, path.basename(path.dirname(p.uri.fsPath))].filter(Boolean).join(' · '), new vscode.Location(p.uri, new vscode.Position(0, 0))));"],
  ["    const items: vscode.CompletionItem[] = [];\n    const inMain = prog.sections.mn", "    const items: vscode.CompletionItem[] = [];\n    const ds = this.s.data.dataset(doc.uri);\n    const inMain = prog.sections.mn"],
  ["        for (const pr of [...this.s.data.posregs.values()].filter(x => x.group === 1)) {", "        for (const pr of [...(ds?.posregs.values() ?? [])].filter(x => x.group === 1)) {"],
  ["        for (const r of this.s.data.numregs.values()) {", "        for (const r of ds?.numregs.values() ?? []) {"],
  ["        for (const r of this.s.data.strregs.values()) {", "        for (const r of ds?.strregs.values() ?? []) {"],
  ["        for (const e of this.s.data.io.values()) {", "        for (const e of ds?.io.values() ?? []) {"],
  ["      for (const p of this.s.index.list()) {\n        if (p.name === programNameFromUri(doc.uri)) continue;", "      const scoped = this.s.index.list(doc.uri);\n      for (const p of scoped.length ? scoped : this.s.index.list()) {\n        if (p.name === programNameFromUri(doc.uri)) continue;"],
  ["      for (const m of this.s.data.macros.values()) {", "      for (const m of ds?.macros.values() ?? []) {"],
  ["      const callers = this.s.index.callers(prog.header.name);\n      const lens = new vscode.CodeLens(spanToRange(prog.header.nameSpan));", "      const callers = this.s.index.callers(prog.header.name, doc.uri);\n      const lens = new vscode.CodeLens(spanToRange(prog.header.nameSpan));"],
  ["          const pr = this.s.data.posreg(t.index);\n          if (pr?.comment) { const h", "          const pr = this.s.data.posreg(t.index, 1, doc.uri);\n          if (pr?.comment) { const h"],
  ["        const c = this.s.data.comment(d.kind, d.index) ?? this.s.index.inlineComment(d.kind, d.index)?.comment;", "        const c = this.s.data.comment(d.kind, d.index, doc.uri) ?? this.s.index.inlineComment(d.kind, d.index, doc.uri)?.comment;"],
  ["placeholder: this.s.data.comment(t.ref.kind, t.ref.index) ?? '' };", "placeholder: this.s.data.comment(t.ref.kind, t.ref.index, doc.uri) ?? '' };"],
  ["import * as vscode from 'vscode';\nimport { type TpProgram, type TpDataRef, type Span, findLabel", "import * as vscode from 'vscode';\nimport * as path from 'node:path';\nimport { type TpProgram, type TpDataRef, type Span, findLabel"],
]);
patch('packages/fanuc/src/tp/diagnostics.ts', [
  ["if (config<boolean>('tp.diagnostics.missingPrograms', true, doc) && s.index.programs.size > 0) {", "if (config<boolean>('tp.diagnostics.missingPrograms', true, doc) && s.index.programCount > 0) {"],
  ["      if (!s.index.get(c.name)) add(spanToRange(c.span), `Program \"${c.name}\" was not found in the workspace or backup folders.`, I, CODES.missingProg);", "      if (!s.index.get(c.name, doc.uri)) add(spanToRange(c.span), `Program \"${c.name}\" was not found in this robot's folder or anywhere in the workspace.`, I, CODES.missingProg);\n      else if (s.index.list(doc.uri).length && !s.index.list(doc.uri).some(p => p.name === c.name.toUpperCase())) add(spanToRange(c.span), `Program \"${c.name}\" exists in another robot's folder but not in this one.`, I, CODES.missingProg);"],
  ["    if (s.data.macros.size > 0) {\n      for (const m of prog.macros) {\n        const entry = s.data.macro(m.name);", "    const ds = s.data.dataset(doc.uri);\n    if (ds && ds.macros.size > 0) {\n      for (const m of prog.macros) {\n        const entry = ds.macro(m.name);"],
  ["        else if (!s.index.get(entry.progName)) add(", "        else if (!s.index.get(entry.progName, doc.uri)) add("],
  ["      const ctrl = s.data.comment(d.kind, d.index);", "      const ctrl = s.data.comment(d.kind, d.index, doc.uri);"],
]);
patch('packages/fanuc/src/tp/commands.ts', [
  ["    const locs = await callSitesOf(s, name);\n    const doc = await vscode.workspace.openTextDocument(uri);", "    const locs = await callSitesOf(s, name, uri);\n    const doc = await vscode.workspace.openTextDocument(uri);"],
]);
patch('packages/fanuc/src/karel/providers.ts', [
  ["        const info = this.s.index.get(sym.from);", "        const info = this.s.index.get(sym.from, doc.uri);"],
  ["const info = this.s.index.get(upper); if (info) return new vscode.Location(info.uri, new vscode.Position(0, 0)); }", "const info = this.s.index.get(upper, doc.uri); if (info) return new vscode.Location(info.uri, new vscode.Position(0, 0)); }"],
]);
patch('src/extension.ts', [
  ["      vscode.window.setStatusBarMessage(`Robot Code: ${s.index.programs.size} programs, ${s.data.numregs.size} R, ${s.data.posregs.size} PR, ${s.data.io.size} I/O points indexed`, 5000);", "      vscode.window.setStatusBarMessage(`Robot Code: ${s.index.programCount} programs in ${s.index.groups().size} folder(s); controller data for ${s.data.datasets.length} robot folder(s)`, 5000);"],
  ["    s.output.appendLine(`[Robot Code] indexed ${s.index.programs.size} programs; controller data: ${s.data.sources.map(x => `${x.kind} (${x.entries})`).join(', ') || 'none'}`);", "    s.output.appendLine(`[Robot Code] indexed ${s.index.programCount} programs in ${s.index.groups().size} folder(s); controller data: ${s.data.datasets.map(d => `${d.label} (${d.sources.length} files)`).join(', ') || 'none'}`);"],
]);
patch('packages/fanuc/src/tp/callGraph.ts', [
  ["export async function showCallGraph(ctx: vscode.ExtensionContext, s: Services, uri?: vscode.Uri) {\n  let root: string | undefined;\n  if (uri) {\n    const doc = await vscode.workspace.openTextDocument(uri);\n    root = s.tp.get(doc).header.name?.toUpperCase() ?? programNameFromUri(uri);\n  } else {\n    const pick = await vscode.window.showQuickPick(s.index.list().map(p => ({ label: p.name, description: p.comment })), { placeHolder: 'Program to graph' });\n    if (!pick) return;\n    root = pick.label;\n  }\n  const key = root;", "export async function showCallGraph(ctx: vscode.ExtensionContext, s: Services, uri?: vscode.Uri) {\n  let root: string | undefined;\n  let near: vscode.Uri | undefined = uri;\n  if (uri) {\n    const doc = await vscode.workspace.openTextDocument(uri);\n    root = s.tp.get(doc).header.name?.toUpperCase() ?? programNameFromUri(uri);\n  } else {\n    const pick = await vscode.window.showQuickPick(s.index.list().map(p => ({ label: p.name, description: [p.comment, path.basename(path.dirname(p.uri.fsPath))].filter(Boolean).join(' · '), uri: p.uri })), { placeHolder: 'Program to graph', matchOnDescription: true });\n    if (!pick) return;\n    root = pick.label; near = pick.uri;\n  }\n  const key = `${root}@${near ? s.index.groupOf(near) : ''}`;"],
  ["    panel = vscode.window.createWebviewPanel('robotCode.callGraph', `Call graph: ${root}`,", "    panel = vscode.window.createWebviewPanel('robotCode.callGraph', `Call graph: ${root}${near && s.index.groups().size > 1 ? ` (${path.basename(path.dirname(near.fsPath))})` : ''}`,"],
  ["      const info = s.index.get(m.open);\n      if (info) await vscode.window.showTextDocument", "      const info = s.index.get(m.open, near);\n      if (info) await vscode.window.showTextDocument"],
  ["    const sub = s.index.onDidChange(() => { if (panels.get(key) === panel) panel!.webview.html = render(build(s, key)); });", "    const sub = s.index.onDidChange(() => { if (panels.get(key) === panel) panel!.webview.html = render(build(s, root!, near)); });"],
  ["  panel.webview.html = render(build(s, root));\n  panel.reveal();", "  panel.webview.html = render(build(s, root, near));\n  panel.reveal();"],
  ["function build(s: Services, root: string): { nodes: Node[]; edges: Edge[]; root: string } {", "function build(s: Services, root: string, near?: vscode.Uri): { nodes: Node[]; edges: Edge[]; root: string } {"],
  ["  const mk = (name: string, layer: number): Node => {\n    const info = s.index.get(name);", "  const mk = (name: string, layer: number): Node => {\n    const info = s.index.get(name, near);"],
  ["    const info = s.index.get(name);\n    if (!info || depth >= 5) continue;\n    const targets: Array<{ to: string; macro?: boolean }> = info.calls.map(c => ({ to: c }));\n    for (const m of info.macros) { const e = s.data.macro(m); if (e)", "    const info = s.index.get(name, near);\n    if (!info || depth >= 5) continue;\n    const targets: Array<{ to: string; macro?: boolean }> = info.calls.map(c => ({ to: c }));\n    for (const m of info.macros) { const e = s.data.macro(m, near); if (e)"],
  ["  for (const c of s.index.callers(root)) { mk(c.name, -1); addEdge(c.name, root); }\n  for (const p of s.index.list()) {\n    for (const m of p.macros) { const e = s.data.macro(m); if (e", "  for (const c of s.index.callers(root, near)) { mk(c.name, -1); addEdge(c.name, root); }\n  for (const p of s.index.list(near)) {\n    for (const m of p.macros) { const e = s.data.macro(m, near); if (e"],
  ["import * as vscode from 'vscode';\nimport { Services } from '../../core/services';", "import * as vscode from 'vscode';\nimport * as path from 'node:path';\nimport { Services } from '../../core/services';"],
]);
patch('packages/core/src/tools/index.ts', [
  ["    const progs = s.index.list().filter(p => p.kind === 'tp');\n    if (!progs.length) { vscode.window.showInformationMessage('No TP programs indexed. Open a folder with .ls files or add a backup folder.'); return; }", "    let progs = s.index.list().filter(p => p.kind === 'tp');\n    if (!progs.length) { vscode.window.showInformationMessage('No TP programs indexed. Open a folder with .ls files or add a backup folder.'); return; }\n    const groups = s.index.groups();\n    if (groups.size > 1) {\n      const items = [...groups.entries()].map(([g, ps]) => ({ label: s.data.dataset(ps[0].uri)?.label ?? path.basename(g), description: `${ps.length} programs · ${g}`, group: g })).sort((a, b) => a.label.localeCompare(b.label));\n      const pick = await vscode.window.showQuickPick(items, { placeHolder: 'Robot folder to cross-reference', matchOnDescription: true });\n      if (!pick) return;\n      progs = progs.filter(p => p.group === pick.group);\n    }\n    const near = progs[0]?.uri;"],
  ["    const entries = buildXref(parsed, (k, i) => s.data.comment(k, i));", "    const entries = buildXref(parsed, (k, i) => s.data.comment(k, i, near));"],
  ["  for (const src of s.data.sources) candidates.add(path.dirname(src.file));", "  for (const ds of s.data.datasets) candidates.add(ds.folder);"],
]);
