/PROG  PROGA
/ATTR
LINE_COUNT	= 3;
/MN
   1:  J P[1] 100% FINE ;
   2:  R[1]=1 ;
   3:  L P[2] 500mm/sec CNT100 ;
/POS
P[1]{
   GP1:
	UF : 1, UT : 1,
	X =  100.000  mm,
	Y =  200.000  mm,
	Z =  300.000  mm,
	W =     0.000 deg,
	P =     0.000 deg,
	R =     0.000 deg
};
P[2]{
   GP1:
	UF : 1, UT : 1,
	X =  500.000  mm,
	Y =  600.000  mm,
	Z =  700.000  mm,
	W =     0.000 deg,
	P =     0.000 deg,
	R =     0.000 deg
};
/END
